language: python
python:
  - "3.8"
install:
  - pip install poetry
  - poetry install
script:
  - poetry run flake8 ./ --exclude venv,build,dist --statistics
  - poetry run safety check --bare
  - poetry run pytest --cov=ytdl tests/*.py
  - coveralls
